server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/crowdcontroller.ddns.net/keystore.p12
    key-store-password: ga8i8MCaC496ysEjS@ZYy7^k$Wn7TgS&
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl: true

spring:
  datasource:
    url: jdbc:mysql://crowdcontroller.ddns.net:3306/crowd_controller?useSSL=false
    username: root
    password: '*stb098*'

logging:
  file: /var/crowdcontroller/logs/crowdcontroller.log
  level:
    me.cooper.rick: DEBUG