server:
  port: 9098

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://helios.csesalford.com:3306/stb098_crowdcontroller?useSSL=false
    username: stb098
    password: '*stb098*'