server:
  port: 9098

spring:
  jpa:
    hibernate:
      ddl-auto: create
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://helios.csesalford.com:3306/stb098_crowdcontroller?useSSL=false
    username: stb098
    password: '*stb098*'
  http:
    converters:
      preferred-json-mapper: gson

security:
  signing-key: MaYzkSjmkzPC57L
  security-realm: Ricks Realm
  oauth2:
    resource:
      filter-order: 3
  jwt:
    client-id: crowdcontrollerclientid
    client-secret: IKUJENFiewf8124ensdcfwfSDF
    grant-types: password
    scope-read: read
    scope-write: write
    resource-ids: ricksResourceId
    validity: 0

management:
  context-path: /actuator
  security:
    enabled: false

endpoints:
  shutdown:
    enabled: true
    sensitive: false

logging:
  level:
    root: INFO
    me.cooper.rick: DEBUG
